version: '3.8'

services:
  elixir:
    image: elixir
    container_name: elixir_container
    stdin_open: true # keep stdin open even if not attached
    tty: true # allocate a pseudo-TTY
    volumes:
      - ./program:/home/program
    command: bash